/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6;

/**
 *
 * @author Sandralio
 */
public class pratikum1 extends javax.swing.JFrame {

    /**
     * Creates new form pratikum1
     */
    public pratikum1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        dokter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jeniskelamin = new javax.swing.JTextField();
        goldarah = new javax.swing.JTextField();
        kewarganegaraan = new javax.swing.JTextField();
        waktupraktek = new javax.swing.JTextField();
        dokterspesial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "DR.Farras Yassar", "DR.Dian Sikahita", "DR.Harun Ulum Fajar" }));
        dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterActionPerformed(evt);
            }
        });
        getContentPane().add(dokter);
        dokter.setBounds(140, 60, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("   Pemilihan Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 0, 140, 50);

        jLabel3.setText("Pilih Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 60, 80, 30);

        jLabel4.setText("Dokter spesial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 470, 90, 30);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(200, 150, 140, 30);
        getContentPane().add(alamat);
        alamat.setBounds(200, 190, 140, 30);
        getContentPane().add(usia);
        usia.setBounds(200, 230, 140, 30);
        getContentPane().add(status);
        status.setBounds(200, 350, 140, 30);
        getContentPane().add(jeniskelamin);
        jeniskelamin.setBounds(200, 270, 140, 30);
        getContentPane().add(goldarah);
        goldarah.setBounds(200, 310, 140, 30);
        getContentPane().add(kewarganegaraan);
        kewarganegaraan.setBounds(200, 390, 140, 30);
        getContentPane().add(waktupraktek);
        waktupraktek.setBounds(200, 430, 140, 30);
        getContentPane().add(dokterspesial);
        dokterspesial.setBounds(200, 470, 140, 30);

        jLabel5.setText("Identitas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 110, 50, 30);

        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 150, 90, 30);

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 190, 90, 30);

        jLabel8.setText("Umur");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 230, 90, 30);

        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 270, 110, 30);

        jLabel10.setText("Golongan Darah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 310, 110, 30);

        jLabel11.setText("Status");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 350, 80, 30);

        jLabel12.setText("Kewarganegaraan");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 390, 120, 30);

        jLabel13.setText("Waktu praktek");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 430, 100, 30);

        setBounds(0, 0, 451, 572);
    }// </editor-fold>//GEN-END:initComponents

    private void dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterActionPerformed
        // TODO add your handling code here:
       if(dokter.getSelectedItem().equals("DR.Farras Yassar")){
           nama.setText("DR.Farras Yassar");
           alamat.setText("jl.Surabaya 16, Malang ");
           usia.setText("20 tahun");
           jeniskelamin.setText("Laki-laki");
           goldarah.setText("A");
           status.setText("belum menikah");
           kewarganegaraan.setText("Indonsia");
           waktupraktek.setText("dokter umum");
           dokterspesial.setText("pagi(07.00-15.00)");
        }
        else 
            if(dokter.getSelectedItem().equals("DR.Dian Sikahita")){
           nama.setText("DR.Dian Sikahita");
           alamat.setText("jl.Veteran 3,malang");
           usia.setText("20 tahun");
           jeniskelamin.setText("Perempuan");
           goldarah.setText("O");
           status.setText("belum menikah");
           kewarganegaraan.setText("Indonsia");
           waktupraktek.setText("dokter gigi");
           dokterspesial.setText("pagi(16.00-2.00)");
            }
            else 
            if(dokter.getSelectedItem().equals("DR.Harun Ulum Fajar")){
           nama.setText("DR.Harun Ulum Fajar");
           alamat.setText("jl.Bandung 9, Malang ");
           usia.setText("20 tahun");
           jeniskelamin.setText("Laki-laki");
           goldarah.setText("B");
           status.setText("belum menikah");
           kewarganegaraan.setText("Indonsia");
           waktupraktek.setText("dokter Gizi");
           dokterspesial.setText("pagi(22.00-06.00)");
                }
    }//GEN-LAST:event_dokterActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pratikum1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> dokter;
    private javax.swing.JTextField dokterspesial;
    private javax.swing.JTextField goldarah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jeniskelamin;
    private javax.swing.JTextField kewarganegaraan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktupraktek;
    // End of variables declaration//GEN-END:variables
}
