/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6;

/**
 *
 * @author Sandralio
 */
public class pratikum2 extends javax.swing.JFrame {
String jns = "";
int jml;

    public pratikum2() {
        initComponents();
        getjumlah();
        setjenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        ket.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        pilihanbil = new javax.swing.JComboBox<>();
        bil4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        b4 = new javax.swing.JTextField();
        bil1 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        jLabel1.setText("        PROGRAM ARITMATIKA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(105, 46, 172, 38);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(572, 199, 59, 20);

        panel.setLayout(null);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(130, 30, 150, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(20, 160, 70, 38);

        jLabel9.setText("      Jenis Aritmatika");
        panel.add(jLabel9);
        jLabel9.setBounds(0, 30, 110, 38);
        panel.add(ket);
        ket.setBounds(100, 0, 60, 40);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(20, 100, 70, 38);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(20, 130, 70, 38);
        panel.add(hasil);
        hasil.setBounds(100, 270, 160, 70);
        panel.add(b1);
        b1.setBounds(130, 70, 110, 30);
        panel.add(b2);
        b2.setBounds(130, 110, 110, 30);
        panel.add(b3);
        b3.setBounds(130, 150, 110, 30);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2);
        jButton2.setBounds(130, 230, 110, 30);
        panel.add(b4);
        b4.setBounds(130, 190, 110, 30);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(20, 70, 60, 40);

        jPanel1.add(panel);
        panel.setBounds(40, 160, 290, 350);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan ", "Pengurangan", "Perkalian", "Pembagian", " " }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(190, 100, 150, 30);

        jLabel8.setText("           Jenis Aritmatika");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 90, 172, 38);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 540);

        setBounds(0, 0, 421, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setjenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
      getjumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Double hs1 = 0.0;
       Double a1, a2, a3, a4;
       a1 = Double.parseDouble(b1.getText().toString());
       a2 = Double.parseDouble(b2.getText().toString());
       a3 = Double.parseDouble(b3.getText().toString());
       a4 = Double.parseDouble(b4.getText().toString());
       
       if(jns.equals("Penjumlahan")) {
           if(jml == 2){
               hs1 = a1 + a2;
               hasil.setText(""+a1 + "+" + a2 + " = " + hs1);
           }
            if(jml == 3){
                hs1 = a1 + a2 + a3;
               hasil.setText(""+a1 + "+" + a2 +"+ " + a3 + " = " + hs1);
           }
            if(jml == 4){
                hs1 = a1 + a2 + a3 + a4;
               hasil.setText(""+a1 + "+" + a2 +"+ " + a3 + "+ " + a4 + " = " + hs1);
           }
       }
       else if (jns.equals("Pengurangan")) {
           if(jml == 2) {
               hs1 = a1 - a2;
               hasil.setText(""+a1 + " - " + a2 + " = " + hs1);
           }
            if(jml == 3){
                hs1 = a1 - a2 - a3;
               hasil.setText(""+a1 + "-" + a2 + " - " + a3 + " = " + hs1);
           }
            if(jml == 4){
                hs1 = a1 - a2 - a3 - a4;
               hasil.setText(""+a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hs1);
           }
       }
    }//GEN-LAST:event_jButton2ActionPerformed
public void getjumlah(){
    if(pilihanbil.getSelectedItem().equals("2")){
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 2;
    }else if (pilihanbil.getSelectedItem().equals("3")){
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(false);
        b4.setVisible(false);
        jml = 3;
     }else if (pilihanbil.getSelectedItem().equals("4")){
        bil4.setVisible(true);
        bil3.setVisible(true);
        b4.setVisible(true);
        b3.setVisible(true);
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        jml = 4;
}
}
    public void setjenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else  if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
         else  if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
         else  if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pratikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables
}
